#!/bin/bash

trap cleanup SIGINT

cleanup(){
  kill $pid_a; kill $pid_b; kill $pid_c
  kill 0
}

connect(){
  ssh -f -nNT -L 9022:diskstation.local:22 gerty
  ssh -f -nNT -L 9548:diskstation.local:548 gerty
  ssh -f -nNT -L 5000:diskstation.local:5000 gerty
  pid_a=$(ps aux | grep 9022:diskstation.local:22 | grep gerty | head -n1 | awk '{print $2;}')
  pid_b=$(ps aux | grep 9548:diskstation.local:548 | grep gerty | head -n1 | awk '{print $2;}')
  pid_c=$(ps aux | grep 5000:diskstation.local:5000 | grep gerty | head -n1 | awk '{print $2;}')
  echo "SSH  > localhost:9022 [PID: $(echo $pid_a)]"
  echo "AFP  > localhost:9548 [PID: $(echo $pid_b)]"
  echo "HTTP > localhost:5000 [PID: $(echo $pid_c)]"
  echo "Press Ctrl+C to close the connections"
}

connect

while true; do
  sleep 10
done
